language: ruby
rvm:
  - 2.1
install: gem install github-pages
before_script: npm install
script:
  - npm run lint:yaml
  - jekyll build
  - npm start
#  - diff -r _site build
#  - diff -r _site export
